#ifndef WEBPAGE_H
#define WEBPAGE_H

static const char *HTML_PAGE =
"<!DOCTYPE html><html lang='pl'><head>"
"<meta charset='UTF-8'>"
"<meta name='viewport' content='width=device-width,initial-scale=1'>"
"<title>Interfejs Sterowania V6</title>"
"<style>"
"body{font-family:system-ui,-apple-system,sans-serif;background-color:#f4f5f7;color:#172b4d;margin:0;padding:20px;display:flex;justify-content:center}"
".app-container{display:flex;flex-wrap:wrap;max-width:1350px;width:100%;gap:25px}"
".sidebar{width:320px;background:#fff;border:1px solid #dfe1e6;border-radius:6px;padding:20px;box-shadow:0 1px 3px rgba(9,30,66,0.05);height:fit-content}"
".sidebar-title{font-size:1rem;font-weight:600;color:#091e42;border-bottom:2px solid #ebecf0;padding-bottom:10px;margin-top:0;text-transform:uppercase}"
".module-card{background:#fafbfc;border:1px solid #dfe1e6;border-radius:4px;padding:15px;margin-bottom:15px}"
".module-label{font-size:0.75rem;font-weight:700;color:#5e6c84;text-transform:uppercase;margin-bottom:5px}"
".module-val{font-size:1.4rem;font-weight:500;color:#172b4d;display:flex;align-items:center}"
".dot{width:10px;height:10px;border-radius:50%;margin-right:10px;background:#c1c7d0}"
".dot.active{background:#36b37e} .dot.warn{background:#ff991f} .dot.err{background:#ff5630}"
".main-canvas{flex:1;background:#fff;border:1px solid #dfe1e6;border-radius:6px;padding:20px;box-shadow:0 1px 3px rgba(9,30,66,0.05)}"
".canvas-title{font-size:1.1rem;font-weight:600;color:#0052cc;margin-top:0;border-bottom:1px solid #ebecf0;padding-bottom:10px;margin-bottom:20px}"
".loop-container{border-left:4px solid #0052cc;padding-left:15px;margin-left:5px}"
".rule-container{background:#fff;border:1px solid #dfe1e6;border-radius:4px;padding:15px;margin-bottom:15px;position:relative;box-shadow:0 1px 2px rgba(0,0,0,0.05)}"
".rule-row{display:flex;align-items:center;flex-wrap:wrap;gap:10px;margin-bottom:8px;padding:12px;background:#f4f5f7;border-radius:4px}"
".rule-row.if{border-left:4px solid #0052cc} .rule-row.then{border-left:4px solid #36b37e} .rule-row.else{border-left:4px solid #ff991f}"
".logic-label{font-weight:700;font-size:0.85rem;color:#5e6c84;width:80px;text-transform:uppercase}"
"select,input{padding:8px 12px;border:1px solid #dfe1e6;border-radius:3px;background:#fff;color:#091e42;font-size:0.9rem;outline:none}"
"select:focus,input:focus{border-color:#4c9aff}"
"input[type='number']{width:75px;text-align:center}"
".btn{padding:12px 20px;border:none;border-radius:3px;font-weight:600;cursor:pointer;font-size:0.95rem;transition:background 0.2s}"
".btn-add{background:#ebecf0;color:#42526e;width:100%;margin-bottom:15px}"
".btn-add:hover{background:#dfe1e6}"
".btn-save{background:#0052cc;color:#fff;width:100%;font-size:1.1rem;padding:15px}"
".btn-save:hover{background:#0043ce}"
".btn-del{position:absolute;top:10px;right:10px;background:none;color:#ff5630;border:none;font-weight:bold;cursor:pointer;font-size:0.85rem}"
".btn-del:hover{text-decoration:underline}"
".logic-link{background:#deebff; color:#0747a6; font-weight:bold; padding:5px 10px; border-radius:15px; font-size:0.8rem; cursor:pointer; user-select:none; margin-left:10px}"
"@media (max-width: 768px) { .sidebar{width:100%;} }"
"</style></head><body>"
"<div class='app-container'>"

"  <div class='sidebar'>"
"    <h3 class='sidebar-title'>Stan komponentów</h3>"
"    <div class='module-card'><div class='module-label'>Diagnostyka I2C</div><div class='module-val' style='font-size:0.85rem; color:#5e6c84; display:block;' id='i2c-box'>Ładowanie...</div></div>"
"    <div class='module-card'><div class='module-label'>Dystans</div><div class='module-val'><div class='dot active'></div><span id='d'>-- mm</span></div></div>"
"    <div class='module-card'><div class='module-label'>Czujnik Odbicia</div><div class='module-val'><div class='dot' id='o-dot'></div><span id='o'>--</span></div></div>"
"    <div class='module-card'><div class='module-label'>Silniki</div><div class='module-val'><div class='dot' id='m-dot'></div><span id='m'>--</span></div></div>"
"    <div class='module-card'><div class='module-label'>Zmienne - kliknij by zmienić nazwę.</div><div class='module-val' style='display:block; width:100%;' id='flags-box'>--</div></div>"
"  </div>"

"  <div class='main-canvas'>"
"    <h3 class='canvas-title'>Główna Pętla Programu</h3>"
"    <div class='loop-container'>"
"       <div id='rules-wrapper'></div>"
"       <button class='btn btn-add' onclick='addRule()'>+ Dodaj Logikę</button>"
"    </div>"
"    <button class='btn btn-save' onclick='saveRules()'>Zapisz program</button>"
"  </div>"

"</div>"
"<script>"
"const flagNames = JSON.parse(localStorage.getItem('fn')) || ['Flaga 1','Flaga 2','Flaga 3','Flaga 4','Flaga 5'];"
"function ren(i){"
"  let n = prompt('Wpisz własną nazwę flagi:', flagNames[i]);"
"  if(n){ flagNames[i]=n.substring(0,25); localStorage.setItem('fn', JSON.stringify(flagNames)); location.reload(); }"
"}"

"const d=document.getElementById('d'); const o=document.getElementById('o'); const m=document.getElementById('m');"
"const odot=document.getElementById('o-dot'); const mdot=document.getElementById('m-dot'); const fbox=document.getElementById('flags-box');"
"const i2cbox=document.getElementById('i2c-box');"

"setInterval(() => {"
"  fetch('/api/stat').then(r=>r.json()).then(j => {"
"    d.innerText=(j.d==='OOR')?'Zasięg maks.':j.d+' mm';"
"    if(j.o===1){ o.innerText='Wykryto'; odot.className='dot err'; } else { o.innerText='Brak'; odot.className='dot active'; }"
"    if(j.m===1){ m.innerText='W ruchu'; mdot.className='dot active'; } else { m.innerText='Stop'; mdot.className='dot'; }"
"    if(j.i2c) i2cbox.innerText = j.i2c;"
"    let html = '';"
"    for(let i=0; i<5; i++) html += \"<div style='display:flex;justify-content:space-between;margin-bottom:8px;font-size:0.95rem;'><span style='cursor:pointer;color:#0052cc;text-decoration:underline;' onclick='ren(\"+i+\")' title='Kliknij aby zmienić nazwę!'>\"+flagNames[i]+\"</span><strong>[\"+j.f[i]+\"]</strong></div>\";"
"    fbox.innerHTML = html;"
"  }).catch(e=>{});"
"}, 300);"

"function updateRuleUI(el) {"
"  const b = el.parentElement;"
"  const op = b.querySelector('.op'); const th = b.querySelector('.th'); const bin = b.querySelector('.bin-val');"
"  if(el.value==='2') { op.style.display='none'; op.value='2'; th.style.display='none'; bin.style.display=''; }"
"  else { op.style.display=''; th.style.display=''; bin.style.display='none'; }"
"}"
"function updateRuleUI2(el) {"
"  const b = el.parentElement;"
"  const op = b.querySelector('.op2'); const th = b.querySelector('.th2'); const bin = b.querySelector('.bin-val2');"
"  if(el.value==='2') { op.style.display='none'; op.value='2'; th.style.display='none'; bin.style.display=''; }"
"  else { op.style.display=''; th.style.display=''; bin.style.display='none'; }"
"}"

"function updateTimeUI(el) { el.nextElementSibling.style.display = (el.value === '1') ? 'inline-block' : 'none'; }"

"function toggleLogic(el) {"
"  const w2 = el.parentElement.querySelector('.warunek-2');"
"  let state = parseInt(el.getAttribute('data-state')); state = (state + 1) % 3;" 
"  el.setAttribute('data-state', state);"
"  if (state === 0) { el.innerText = '➕ Warunek'; w2.style.display = 'none'; }"
"  if (state === 1) { el.innerText = 'AND (I)'; w2.style.display = 'inline-flex'; }"
"  if (state === 2) { el.innerText = 'OR (LUB)'; w2.style.display = 'inline-flex'; }"
"}"

"function addRule() {"
"  const wrapper = document.getElementById('rules-wrapper');"
"  const div = document.createElement('div');"
"  div.className = 'rule-container';"
"  div.innerHTML = `"
"    <button class='btn-del' onclick='this.parentElement.remove()'>USUŃ</button>"
"    <div class='rule-row if'>"
"      <span class='logic-label'>JEŚLI</span>"
"      <select class='in' onchange='updateRuleUI(this)'>"
"        <option value='0'>[Wybierz wejście]</option><option value='1'>Dystans (Laser)</option><option value='2'>Odbicie (TCRT)</option>"
"        <option value='3'>${flagNames[0]}</option><option value='4'>${flagNames[1]}</option><option value='5'>${flagNames[2]}</option><option value='6'>${flagNames[3]}</option><option value='7'>${flagNames[4]}</option>"
"      </select>"
"      <select class='op'><option value='0'>&lt; (Mniejsze niż)</option><option value='1'>&gt; (Większe niż)</option><option value='2'>== (Równe)</option></select>"
"      <input type='number' class='th' value='150'>"
"      <select class='bin-val' style='display:none;'><option value='1'>Aktywne (Wykryto / ON)</option><option value='0'>Puste (Brak / OFF)</option></select>"
"      <span class='logic-link' data-state='0' onclick='toggleLogic(this)'>➕ Warunek</span>"
"      "
"      <span class='warunek-2' style='display:none; align-items:center; gap:5px; margin-left:10px; border-left: 2px solid #dfe1e6; padding-left:10px;'>"
"        <select class='in2' onchange='updateRuleUI2(this)'><option value='0'>[Wybierz wejście]</option><option value='1'>Dystans (Laser)</option><option value='2'>Odbicie (TCRT)</option><option value='3'>${flagNames[0]}</option><option value='4'>${flagNames[1]}</option><option value='5'>${flagNames[2]}</option><option value='6'>${flagNames[3]}</option><option value='7'>${flagNames[4]}</option></select>"
"        <select class='op2'><option value='0'>&lt;</option><option value='1'>&gt;</option><option value='2'>==</option></select>"
"        <input type='number' class='th2' value='1' style='width:50px;'>"
"        <select class='bin-val2' style='display:none;'><option value='1'>ON</option><option value='0'>OFF</option></select>"
"      </span>"
"    </div>"
"    <div class='rule-row then'>"
"      <span class='logic-label'>TO</span>"
"      <select class='ao'>"
"        <option value='0'>[Brak akcji]</option><option value='1'>Silnik 1</option><option value='2'>Silnik 2</option><option value='3'>Oba silniki</option>"
"        <option value='4'>Ustaw: ${flagNames[0]}</option><option value='5'>Ustaw: ${flagNames[1]}</option><option value='6'>Ustaw: ${flagNames[2]}</option><option value='7'>Ustaw: ${flagNames[3]}</option><option value='8'>Ustaw: ${flagNames[4]}</option>"
"      </select>"
"      <span style='color:#5e6c84;font-size:0.9rem;'>Wartość:</span>"
"      <input type='number' class='av' value='1'>"
"      "
"      <select class='time-mode' onchange='updateTimeUI(this)' style='margin-left:15px; border-color:#dfe1e6;'>"
"        <option value='0'>Działanie ciągłe</option><option value='1'>Włącz na czas:</option>"
"      </select>"
"      <span class='time-input' style='display:none;'><input type='number' class='dur' value='1.5' min='0.1' step='0.1'> <span style='color:#5e6c84;font-size:0.9rem;'>sek</span></span>"
"    </div>"
"    <div class='rule-row else'>"
"      <span class='logic-label'>INACZEJ</span>"
"      <select class='eo'>"
"        <option value='0'>[Brak akcji]</option><option value='1'>Silnik 1</option><option value='2'>Silnik 2</option><option value='3'>Oba silniki</option>"
"        <option value='4'>Ustaw: ${flagNames[0]}</option><option value='5'>Ustaw: ${flagNames[1]}</option><option value='6'>Ustaw: ${flagNames[2]}</option><option value='7'>Ustaw: ${flagNames[3]}</option><option value='8'>Ustaw: ${flagNames[4]}</option>"
"      </select>"
"      <span style='color:#5e6c84;font-size:0.9rem;'>Wartość:</span>"
"      <input type='number' class='ev' value='0'>"
"    </div>"
"  `;"
"  wrapper.appendChild(div);"
"}"

"function saveRules() {"
"  let rules = [];"
"  document.querySelectorAll('.rule-container').forEach(r => {"
"    let inType = r.querySelector('.in').value;"
"    let op = r.querySelector('.op').value;"
"    let th = (inType === '2') ? r.querySelector('.bin-val').value : (r.querySelector('.th').value || 0);"
"    "
"    let inType2 = r.querySelector('.in2').value;"
"    let op2 = r.querySelector('.op2').value;"
"    let th2 = (inType2 === '2') ? r.querySelector('.bin-val2').value : (r.querySelector('.th2').value || 0);"
"    let logicLink = r.querySelector('.logic-link').getAttribute('data-state');"
"    "
"    let ao = r.querySelector('.ao').value;"
"    let av = r.querySelector('.av').value || 0;"
"    let eo = r.querySelector('.eo').value;"
"    let ev = r.querySelector('.ev').value || 0;"
"    "
"    let tMode = r.querySelector('.time-mode').value;"
"    let dur_ms = (tMode === '1') ? Math.floor(parseFloat(r.querySelector('.dur').value) * 1000) : 0;"
"    if(isNaN(dur_ms)) dur_ms = 0;"
"    "
"    rules.push(inType+','+op+','+th+','+inType2+','+op2+','+th2+','+logicLink+','+ao+','+av+','+eo+','+ev+','+dur_ms);"
"  });"
"  const payload = rules.join(';');"
"  fetch('/api/rules', { method: 'POST', body: payload }).then(r => { if(r.ok) alert('Program wgrany.'); else alert('Błąd.'); }).catch(e => alert('Brak łączności.'));"
"}"
"window.onload = () => addRule();"
"</script></body></html>";

#endif // WEBPAGE_H